name: Compile

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        arch: [ amd64, arm64, arm, 386 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: ${{ matrix.arch }}
          cache: 'pdm' # Optional. Options are 'none', 'pdm', 'pip', or 'all'. Default is 'all'

      - name: Install Dependencies
        run: |
          pip install pdm
          pdm install --no-lock

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: server_status/main.py
          onefile: true
          standalone: true
          follow-imports: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*